#!/usr/bin/awk -f

BEGIN {
    alphabet = "abcdefghijklmnopqrstuvwxyz"
    split(alphabet, letters, "")
    # Loop through the letters and assign them a number
    for (i = 1; i <= 26; i++) {
        num[letters[i]] = i - 1
    }
    # Ask the user for the shift value
    print "Enter the shift value:"
    # Read the shift value from the standard input
    getline shift < "-"
    # Make sure the shift value is between 0 and 25
    shift = shift % 26
}

{
    line = tolower($0)
    result = ""
    # Loop through each character of the line
    for (i = 1; i <= length(line); i++) {
        char = substr(line, i, 1)
        if (char ~ /[a-z]/) {
            n = num[char]
            # Shift the number by the given amount
            n = (n + shift) % 26
            char = letters[n + 1]
        }
        # Append the character to the result
        result = result char
    }
    print result
}
